# Generated by Django 5.0.6 on 2024-06-27 05:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("contrase", models.CharField(max_length=30)),
                ("correo", models.CharField(max_length=30)),
                ("direccion", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "idDet",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombreDet", models.CharField(max_length=40)),
                ("fechaCompra", models.DateTimeField()),
                ("fechaEntrega", models.DateTimeField()),
                ("totalD", models.IntegerField()),
                ("descripcionD", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idP", models.AutoField(primary_key=True, serialize=False)),
                ("nombreP", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField()),
                ("valor", models.IntegerField()),
                ("descripcion", models.CharField(max_length=50)),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoMecanico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "idV",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombreV", models.CharField(max_length=40)),
                ("fechaCompra", models.DateTimeField()),
                ("total", models.IntegerField()),
                ("descripcion", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Mecanico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12)),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("edad", models.IntegerField(default=0)),
                ("direccion", models.CharField(max_length=60)),
                ("telefono", models.CharField(max_length=20)),
                ("habilitado", models.BooleanField(default=True)),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="imagen"
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.genero"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tipomecanico",
                    ),
                ),
            ],
        ),
    ]
