# Generated by Django 5.0.4 on 2024-06-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mecanicos'),
        ),
    ]
