# Generated by Django 5.0.4 on 2024-06-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mecanico_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('contrase', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDet', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreDet', models.CharField(max_length=40)),
                ('fechaCompra', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('totalD', models.IntegerField()),
                ('descripcionD', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idV', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreV', models.CharField(max_length=40)),
                ('fechaCompra', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
    ]
